### ISSUE TITLE
Should bots know which bot gave what info?

### ISSUE THREAD

**Issue by akaps** [akaps/hanabi_ai#11]
A question from @C-Saunders that I've been spinning on and want to preserve some thoughts.

If a bot was given new information, it may want to know who gave it to infer something about the meaning of the disclosure. The simplest case is between bots of the same class, where there can be logic like "I tell this kind of info to signal action A. Since I was given that info, I will do action A". Note that this is different from bots that share state between each instance, which we should not encourage.

Is it necessary to know who told you what info for optimal play? Currently there is a known_info field in game_state so bots can determine what was said about each card, but not by whom. Assuming each bot is playing optimally (they should aim to, it's communal scoring), it shouldn't matter who gave the info.

There are cases where you may be trying to give an additional piece of info based on who you are giving info to. If Bot A doesn't give info to the next bot B (A tells C, not B), B can assume they don't have playable/valuable cards right now. If B tracks what info they had about their hand, they should be able to make that assessment without knowing what move A made.

Let's consider the case of a bad actor: Based on how disclosures are implemented, there will never be incorrect info given, just not immediately useful/the most pertinent. If Bot A receives info it thinks is not useful from Bot B, it could try to ignore signaling from Bot B, only if it knew that info came from Bot B. There is a problem in that it needs the other bots to recognize that and tell A info, or A might not play cards the rest of the game. This probably extends to plays as well, since you might not want to give info to a player who is incorrectly interpreting info.

Thoughts? I think I'm arguing that it's redundant and may lead bots to make suboptimal decisions, but if bot designers want extra info, there is very little cost to provide it.

**Comment by C-Saunders** [comment]
I think there may be scenarios where who disclosed what information is important for optimal play, though I'm not sure how important.

Knowing who played and discarded what cards also seems important, though it's a bit out of scope for this issue.

Example scenario - three player game, turn order A, B, C, I am player A.
* I know card X is red
* B discloses to C that card Y is red
* C discards Y because they know it will tell me what I need to act on my known red card
* Since B told C and C was able to act, I might be able to infer X = R4

In this scenario, it seems that knowing who discarded or played what and when is more valuable than know who disclosed what and to whom. It's possible knowing about the disclosures adds no value here, but I'm not sure.

**Comment by akaps** [comment]
Would keeping a list of the previous plays be sufficient? Bots are responsible for parsing the info they care about, but they have the most info and its the least effort

**Comment by akaps** [comment]
merged with 2e9295954ed4ccdb50bc632476b0fffbfbc07772
